name: makecss
on: workflow_dispatch
jobs:
  makecss:
    runs-on: ubuntu-20.04
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    steps:
      - run: |
        python -m pip install libsass --user
        make auto.css classic.css dark.css
