name: makecss
on: workflow_dispatch
jobs:
  makecss:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Compile CSS
        run: |
          python -m pip install libsass --user
          make naiveautoamalgamated.css naiveclassicamalgamated.css naivedarkamalgamated.css naivesolarizedamalgamated.css naivesolarizedlightamalgamated.css naivesolarizeddarkamalgamated.css
          make auto.css classic.css dark.css
          make solarized.css solarized-light.css solarized-dark.css 
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            *.css
